apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: hello-crane-tekton-demo-
spec:
  params:
    - name: src-namespace
      value: nginx-example
    - name: src-context
      value: kind-src
    - name: dest-context
      value: kind-dest
  pipelineSpec:
    params:
      - name: src-namespace
        type: string
      - name: src-context
        type: string
      - name: dest-context
        type: string
    workspaces:
      - name: shared-data
      - name: kubeconfig
      - name: craneconfig
    tasks:
      - name: export
        taskRef:
          name: crane-export
          kind: ClusterTask
        params:
          - name: src-namespace
            value: "$(params.src-namespace)"
          - name: src-context
            value: "$(params.src-context)"
        workspaces:
          - name: export
            workspace: shared-data
            subPath: export
          - name: kubeconfig
            workspace: kubeconfig
      - name: transform
        runAfter:
          - export
        taskRef:
          name: crane-transform
          kind: ClusterTask
        workspaces:
          - name: ignored-patches
            workspace: shared-data
            subPath: ignored-patches
          - name: export
            workspace: shared-data
            subPath: export
          - name: transform
            workspace: shared-data
            subPath: transform
          - name: craneconfig
            workspace: craneconfig
            subPath: config
      - name: apply
        runAfter:
          - transform
        taskRef:
          name: crane-apply
          kind: ClusterTask
        workspaces:
          - name: export
            workspace: shared-data
            subPath: export
          - name: transform
            workspace: shared-data
            subPath: transform
          - name: apply
            workspace: shared-data
            subPath: apply
      - name: import
        runAfter:
          - apply
        taskRef:
          name: crane-import
          kind: ClusterTask
        params:
          - name: src-namespace
            value: "$(params.src-namespace)"
          - name: dest-context
            value: "$(params.dest-context)"
          - name: dest-namespace
            value: "$(context.pipelineRun.namespace)"
        workspaces:
          - name: apply
            workspace: shared-data
            subPath: apply
          - name: kubeconfig
            workspace: kubeconfig
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Mi
    - name: kubeconfig
      secret:
        secretName: kubeconfig
    - name: craneconfig
      configmap:
        name: craneconfig
