apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: crane-transform
spec:
  steps:
    - name: crane-transform
      image: quay.io/djzager/crane-runner:hello-crane
      script: |
        /crane version
        /crane transform \
          --ignored-patches-dir=$(workspaces.ignored-patches.path) \
          --config-file=$(workspaces.craneconfig.path) \
          --export-dir=$(workspaces.export.path) \
          --transform-dir=$(workspaces.transform.path)
        find $(workspaces.transform.path)
        find $(workspaces.ignored-patches.path)
  # https://github.com/tektoncd/pipeline/blob/main/docs/workspaces.md#using-workspaces-in-tasks
  workspaces:
    - name: ignored-patches
      description: |
        This is the folder where the results of crane ignored-patches were stored.
      mountPath: /var/crane/ignored-patches
    - name: export
      description: |
        This is the folder where the results of crane export were stored.
      mountPath: /var/crane/export
    - name: transform
      description: |
        This is the folder where we will store the results of crane transform.
      mountPath: /var/crane/transform
    - name: craneconfig
      description: |
        This is where we hold the configuration file for crane.
      mountPath: /var/crane/config
