apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: crane-import
spec:
  params:
    - name: src-namespace
      type: string
      description: The namespace from the source cluster to export.
    - name: dest-context
      type: string
      description: The context from the kubeconfig that represents the destination cluster.
    - name: dest-namespace
      type: string
      description: The namespace we are importing to.
  steps:
    - name: crane-import
      image: quay.io/djzager/crane-runner:hello-crane
      script: |
        pushd $(workspaces.apply.path)/resources
        yamls=$(find . -type f -name \*.yaml)
        echo "namespace: $(params.dest-namespace)" > ./kustomization.yaml
        echo "resources:" >> ./kustomization.yaml
        for file in ${yamls}; do echo "- ${file}" >> ./kustomization.yaml; done
        cat kustomization.yaml

        oc --context $(params.dest-context) apply -k ./
      env:
        - name: KUBECONFIG
          value: $(workspaces.kubeconfig.path)/config
  # https://github.com/tektoncd/pipeline/blob/main/docs/workspaces.md#using-workspaces-in-tasks
  workspaces:
    - name: apply
      description: |
        This is the folder where we will store the results of crane apply.
      mountPath: /var/crane/apply
    - name: kubeconfig
      description: |
        The user's kubeconfig
